# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 19:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0018_auto_20171002_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nombre')),
                ('date_created', models.DateField(default=datetime.date.today, verbose_name='date created')),
                ('max_participants', models.PositiveSmallIntegerField(verbose_name='participantes máximos')),
                ('inscription_end', models.DateField(verbose_name='fin de inscripción')),
            ],
            options={
                'verbose_name': 'Evento',
                'permissions': (('save_event', 'NEW: Can save changes made to the model'),),
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='EventInscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date.today, verbose_name='date created')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Event', verbose_name='evento')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Student', verbose_name='miembro')),
            ],
            options={
                'verbose_name': 'Inscripción a Evento',
                'permissions': (('save_eventinscription', 'NEW: Can save changes made to the model'),),
                'verbose_name_plural': 'Inscripciones a Evento',
            },
        ),
        migrations.AlterUniqueTogether(
            name='eventinscription',
            unique_together=set([('member', 'event')]),
        ),
    ]
