# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='inscription_end',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='fin de inscripción'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='participantes máximos'),
        ),
    ]
