"""
Django settings for CEITBA project.

Generated by 'django-admin startproject' using Django 1.9.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import locale
import os
from collections import OrderedDict

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'n427g1a@wl_-1n(n7s!n)_yy=tq9p-xyxj%rl=*^f#!0t5*itz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin.apps.SimpleAdminConfig',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'facturacion.apps.FacturacionConfig',
    'informacion.apps.InformacionConfig',
    'lockers.apps.LockersConfig',
    'nautica.apps.NauticaConfig',
    'bar.apps.BarConfig',
    'eventos.apps.EventosConfig',

    'constance',
    'constance.backends.database',

    'django_select2',
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CEITBA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CEITBA.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, "media/")

CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

EMAIL_SUBJECT_PREFIX = "[CEITBA] "

CONSTANCE_CONFIG = {
    'CEITBA_SERVICE_NAME': (
        'CEITBA',
        'Nombre del servicio del CEITBA'
    ),
    'YMCA_SERVICE_NAME': (
        'YMCA',
        'Nombre del servicio del YMCA'
    ),
    'GIMNASIO_SERVICE_NAME': (
        'Gimnasio',
        'Nombre del servicio del Gimnasio'
    ),

    'YMCA_MEDICALEXAM_PRODUCT_NAME': (
        'Examen Médico YMCA',
        'Nombre del producto del examen médico del YMCA'
    ),

    'GIMNASIO_GRACE_PERIOD': (
        15,
        'Período de gracia para entregar el apto médico.',
        int
    ),

    'DAY_TO_SEND_REPORT': (
        18,
        'Dia del mes en el que se debe enviar el reporte',
        int
    ),
    'REPORT_ALLOW_IF_WITHIN_RANGE': (
        4,
        'Permitir enviar el reporte esta cantidad de dias antes o despues que DAY_TO_SEND_REPORT',
        int
    ),
    'REPORT_MIN_DISTANCE_IN_DAYS': (
        27,
        'Distancia minima entre reportes en dias',
        int
    ),
    'STUDENT_ID_CHANGE_GRACE_PERIOD': (
        3,
        'Periodo de gracia en el cual se puede modificar el legajo de un alumno',
        int
    ),
    'ITBA_EMAIL_DOMAIN': (
        '@itba.edu.ar',
        'Dominio de los emails del ITBA. Sera usado como validator para los emails de los alumnos',
        str
    ),
    'LOCKER_SEND_MAIL_ON_HOLD': (
        True,
        'Enviar email automaticamente al efectuar una reserva.',
        bool
    ),
    'LOCKER_ENABLE_AUTOHOLD': (
        False,
        'Habilitar sistema de manejo de lockers',
        bool
    ),
    'CEITBA_EMAIL': (
        'ceitba@itba.edu.ar',
        'Email del CEITBA',
        str
    ),
    'IMPRESIONES_GRATIS': (
        100,
        'Impresiones gratis',
        int
    ),
    'IMPRESIONES_PRODUCT': (
        'Impresiones',
        'Nombre del producto de las impresiones'
    ),
    'IMPRESIONES_SEND_EMAIL': (
        True,
        'Enviar email al sobrepasar las IMPRESIONES_GRATIS',
        bool
    ),
    'MATE_PRODUCT_NAME': (
        'Kit mate',
        'Nombre del producto de los kit de mate',
        str
    ),
    'INVENTORY_NOTIFICATIONS': (
        True,
        'Enviar notificaciones por bajo inventario',
        bool
    ),
    'BAR_CACHE_TIMEOUT': (
        30 * 60,
        'Timeout del cache del bar',
        int
    ),
    'YMCA_FAMILYMEMBER_PRODUCT': (
        'Miembro Familiar YMCA',
        'Nombre del producto de los miembros familiares del YMCA'
    ),
}

CONSTANCE_CONFIG_FIELDSETS = OrderedDict([
    ('Configuración de Servicios', (
        'CEITBA_SERVICE_NAME',
        'YMCA_SERVICE_NAME',
        'GIMNASIO_SERVICE_NAME'
    )),
    ('Configuración de Productos', (
        'YMCA_MEDICALEXAM_PRODUCT_NAME',
        'IMPRESIONES_PRODUCT',
        'MATE_PRODUCT_NAME',
        'YMCA_FAMILYMEMBER_PRODUCT'
    )),
    ('Configuración de Reportes', (
        'DAY_TO_SEND_REPORT',
        'REPORT_ALLOW_IF_WITHIN_RANGE',
        'REPORT_MIN_DISTANCE_IN_DAYS'
    )),
    ('Parametros Generales', (
        'GIMNASIO_GRACE_PERIOD',
        'STUDENT_ID_CHANGE_GRACE_PERIOD',
        'ITBA_EMAIL_DOMAIN',
        'CEITBA_EMAIL',
        'BAR_CACHE_TIMEOUT',
        'INVENTORY_NOTIFICATIONS'
    )),
    ('Gestión de Lockers', (
        'LOCKER_SEND_MAIL_ON_HOLD',
        'LOCKER_ENABLE_AUTOHOLD'
    )),
    ('Gestión de Impresiones', (
        'IMPRESIONES_GRATIS',
        'IMPRESIONES_SEND_EMAIL'
    ))
])

MEDIA_OBJECTS_CACHE_TIMEOUT = 0
FILE_UPLOAD_PERMISSIONS = 0o644

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt': "%d/%b/%Y %H:%M:%S"
        },
    },

    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },

    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 99,
            'filename': os.path.join(BASE_DIR, "logs/facturacion.log", ),
            'formatter': 'verbose'
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
        },
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['mail_admins', 'file', 'console'],
            'propagate': True,
            'level': 'DEBUG',
        },
        'django.template': {
            'handlers': ['mail_admins', 'file', 'console'],
            'propagate': False,
            'level': 'INFO',
        },
        'django.db': {
            'handlers': ['mail_admins', 'file', 'console'],
            'propagate': False,
            'level': 'INFO',
        },
        'django.request': {
            'handlers': ['mail_admins', 'file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'facturacion': {
            'handlers': ['mail_admins', 'file', 'console'],
            'propagate': True,
            'level': 'DEBUG',
        },
        'informacion': {
            'handlers': ['mail_admins', 'file', 'console'],
            'propagate': True,
            'level': 'DEBUG',
        },
        'lockers': {
            'handlers': ['mail_admins', 'file', 'console'],
            'propagate': True,
            'level': 'DEBUG',
        },
        'bar': {
            'handlers': ['mail_admins', 'file', 'console'],
            'propagate': True,
            'level': 'DEBUG',
        },
    }
}

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

SITE_ID = 1

INTERNAL_IPS = ['127.0.0.1']
INSTALLED_APPS += ['debug_toolbar']
