# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0003_auto_20160505_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'permissions': (('save_model', 'Can save changes made to the model'),), 'verbose_name': 'Bill', 'verbose_name_plural': 'Bills'},
        ),
        migrations.AlterModelOptions(
            name='billcategory',
            options={'permissions': (('save_model', 'Can save changes made to the model'),), 'verbose_name': 'Bill Category', 'verbose_name_plural': 'Bill Categories'},
        ),
    ]
