# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0004_auto_20160908_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=100, verbose_name='responsable')),
                ('description', models.TextField(max_length=500, verbose_name='description')),
                ('amount_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ingresos')),
                ('amount_out', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='egresos')),
                ('date_created', models.DateField(blank=True, default=None, null=True, verbose_name='fecha de egreso')),
                ('date_paid', models.DateField(blank=True, default=None, null=True, verbose_name='date paid')),
            ],
            options={
                'verbose_name': 'Entrada de Libro Diario',
                'permissions': (('save_model', 'Can save changes made to the model'),),
                'verbose_name_plural': 'Entradas de Libro Diario',
            },
        ),
        migrations.RemoveField(
            model_name='bill',
            name='category',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='BillCategory',
        ),
    ]
