# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 15:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0005_auto_20161129_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateField(db_index=True, default=datetime.date.today, verbose_name='date uploaded')),
                ('file', models.FileField(upload_to='printer_reports/', verbose_name='report file')),
            ],
            options={
                'verbose_name': 'Reporte de impresión',
                'verbose_name_plural': 'Reportes de impresión',
                'permissions': (('save_model', 'Can save changes made to the model'),),
            },
        ),
    ]
