# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 14:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_auto_20161004_1606'),
        ('informacion', '0006_printerreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateField(db_index=True, default=datetime.date.today, verbose_name='date uploaded')),
                ('certificate', models.FileField(upload_to='sport_certificates/', verbose_name='certificate')),
                ('date_emitted', models.DateField(verbose_name='fecha de emisión')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Student', verbose_name='member')),
            ],
            options={
                'verbose_name': 'Certificado médico',
                'permissions': (('save_model', 'Can save changes made to the model'),),
                'verbose_name_plural': 'Certificados médicos',
            },
        ),
        migrations.AlterModelOptions(
            name='printerreport',
            options={'get_latest_by': 'date_uploaded', 'permissions': (('save_model', 'Can save changes made to the model'),), 'verbose_name': 'Reporte de impresión', 'verbose_name_plural': 'Reportes de impresión'},
        ),
        migrations.AlterField(
            model_name='printerreport',
            name='date_uploaded',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='to date'),
        ),
    ]
