# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-21 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_auto_20161004_1606'),
        ('informacion', '0010_auto_20170219_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='count')),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date created')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Student', verbose_name='member')),
            ],
            options={
                'verbose_name': 'Excepcion de Impresion',
                'verbose_name_plural': 'Excepciones de Impresiones',
                'permissions': (('save_model', 'Can save changes made to the model'),),
            },
        ),
    ]
