# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_auto_20161004_1606'),
        ('informacion', '0011_printingexception'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_count', models.PositiveSmallIntegerField(default=0, verbose_name='impresiones')),
                ('last_updated', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Ultima actualizacion')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Student', verbose_name='member')),
            ],
            options={
                'permissions': (('save_model', 'Can save changes made to the model'),),
                'verbose_name': 'Cuenta de Impresión',
                'verbose_name_plural': 'Cuentas de Impresión',
            },
        ),
    ]
