# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0012_printercount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printerreport',
            name='date_uploaded',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='to date'),
        ),
    ]
