# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_auto_20161004_1606'),
        ('informacion', '0013_auto_20170904_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlquilerMate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha alquiler')),
                ('time_returned', models.DateTimeField(null=True, verbose_name='Fecha devolución')),
                ('kit_number', models.PositiveSmallIntegerField(verbose_name='Número de Kit')),
                ('amount_donated', models.PositiveSmallIntegerField(verbose_name='Monto donado')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Student', verbose_name='member')),
            ],
            options={
                'verbose_name': 'Alquiler de Mate',
                'verbose_name_plural': 'Alquileres de Mate',
                'permissions': (('save_model', 'Can save changes made to the model'),),
            },
        ),
        migrations.AlterField(
            model_name='printerreport',
            name='date_uploaded',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date uploaded'),
        ),
    ]
