# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0014_auto_20170905_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportcertificate',
            options={'get_latest_by': 'date_emitted', 'permissions': (('save_model', 'Can save changes made to the model'),), 'verbose_name': 'Certificado médico', 'verbose_name_plural': 'Certificados médicos'},
        ),
    ]
