# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0015_auto_20170905_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquilermate',
            name='paid_in_cash',
            field=models.BooleanField(default=True, help_text='Al desmarcarlo se le agregará una compra equivalente de forma automática.', verbose_name='Paga en Efectivo'),
        ),
        migrations.AlterField(
            model_name='alquilermate',
            name='amount_donated',
            field=models.PositiveSmallIntegerField(default=0, help_text='Dejar en 0 para cobro por cuota.', verbose_name='Monto donado'),
        ),
        migrations.AlterField(
            model_name='alquilermate',
            name='time_returned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha devolución'),
        ),
    ]
