# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0017_auto_20171002_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_time', models.PositiveSmallIntegerField(verbose_name='tiempo en pantalla')),
                ('media_file', models.FileField(upload_to='office_media', verbose_name='archivo multimedia')),
                ('published', models.BooleanField(db_index=True, default=True, verbose_name='publicado')),
            ],
            options={
                'verbose_name': 'Archivo Multimedia',
                'permissions': (('save_mediaobject', 'NEW: Can save changes made to the model'),),
                'verbose_name_plural': 'Archivos Multimedia',
            },
        ),
    ]
