# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0019_remove_inventoryentry_amortization_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, unique=True, verbose_name='ubicación')),
            ],
            options={
                'verbose_name': 'Ubicación de Inventario',
                'permissions': (('save_inventorylocation', 'NEW: Can save changes made to the model'),),
                'verbose_name_plural': 'Ubicaciones de Inventario',
            },
        ),
        migrations.AlterField(
            model_name='inventoryentry',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informacion.InventoryLocation', verbose_name='ubicación'),
        ),
    ]
