# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0021_auto_20171008_1643'),
        ('informacion', '0020_auto_20171006_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryentry',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.Product', verbose_name='producto'),
        ),
    ]
