# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0022_auto_20171024_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediaobject',
            old_name='published',
            new_name='published_tv',
        ),
    ]
