# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0022_auto_20171024_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='titulo')),
                ('document', models.FileField(upload_to='documents', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'permissions': (('save_mediaobject', 'NEW: Can save changes made to the model'),),
            },
        ),
    ]
