# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0027_cashpurchase_cashpurchaseitem'),
        ('informacion', '0024_reminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangedExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='fecha inicio')),
                ('end_date', models.DateField(verbose_name='end_date')),
                ('exported_file', models.FileField(upload_to='ranged_exports', verbose_name='archivo exportado')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Service', verbose_name='servicio')),
            ],
        ),
    ]
