# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0026_auto_20180208_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': (('save_document', 'NEW: Can save changes made to the model'),), 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='rangedexport',
            options={'permissions': (('save_rangedexport', 'NEW: Can save changes made to the model'),), 'verbose_name': 'Exportar por Rango', 'verbose_name_plural': 'Exportar por Rango'},
        ),
        migrations.AlterModelOptions(
            name='reminder',
            options={'permissions': (('save_reminder', 'NEW: Can save changes made to the model'),), 'verbose_name': 'Recordatorio', 'verbose_name_plural': 'Recordatorios'},
        ),
    ]
