# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-07 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
       # ('informacion', '0024_auto_20171127_1233'),
        ('informacion', '0027_auto_20180208_1140'),
    ]

    operations = [
    ]
