# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='billable',
            field=models.BooleanField(default=True, help_text="Unmark if this enrollment shouldn't be included in a report.", verbose_name='billable'),
        ),
    ]
