# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_auto_20160505_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AddField(
            model_name='student',
            name='type',
            field=models.CharField(choices=[('S', 'Student'), ('F', 'Staff'), ('E', 'Ex Student')], default='S', max_length=1, verbose_name='type'),
        ),
    ]
