# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_auto_20160506_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'permissions': (('save_model', 'Can save changes made to the model'),), 'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('save_model', 'Can save changes made to the model'),), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'permissions': (('save_model', 'Can save changes made to the model'),), 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'permissions': (('save_model', 'Can save changes made to the model'),), 'verbose_name': 'Purchase Item', 'verbose_name_plural': 'Purchase Items'},
        ),
        migrations.AlterModelOptions(
            name='reimbursement',
            options={'get_latest_by': 'date_created', 'permissions': (('save_model', 'Can save changes made to the model'),), 'verbose_name': 'Reimbursement', 'verbose_name_plural': 'Reimbursements'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'get_latest_by': 'date_created', 'permissions': (('save_model', 'Can save changes made to the model'),), 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'permissions': (('save_model', 'Can save changes made to the model'),), 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('save_model', 'Can save changes made to the model'),), 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
    ]
