# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_auto_20160507_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_staff_file',
            field=models.FileField(default=None, upload_to='reports/', verbose_name='staff report file', null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='name'),
        ),
    ]
