# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_auto_20160510_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paid', models.DateField(blank=True, db_index=True, default=None, null=True, verbose_name='date paid')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Enrollment', verbose_name='enrollment')),
            ],
            options={
                'verbose_name': 'Debt',
                'verbose_name_plural': 'Debts',
            },
        ),
    ]
