# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_debt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'permissions': (('save_model', 'Can save changes made to the model'),), 'verbose_name': 'Debt', 'verbose_name_plural': 'Debts'},
        ),
        migrations.AlterField(
            model_name='student',
            name='type',
            field=models.CharField(choices=[('S', 'Student'), ('F', 'Staff'), ('E', 'Ex Student'), ('X', 'Exchange')], default='S', max_length=1, verbose_name='type'),
        ),
    ]
