# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_auto_20160517_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='enrollment',
        ),
        migrations.DeleteModel(
            name='Debt',
        ),
    ]
