# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 12:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_auto_20160518_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(db_index=True, default=datetime.date.today, verbose_name='date created')),
                ('date_paid', models.DateField(blank=True, db_index=True, default=None, null=True, verbose_name='date paid')),
                ('enrollments', models.ManyToManyField(to='facturacion.Enrollment', verbose_name='enrollments')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'Debt',
                'verbose_name_plural': 'Debts',
                'permissions': (('save_model', 'Can save changes made to the model'),),
            },
        ),
    ]
