# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='from_report',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.Report', verbose_name='from report'),
        ),
    ]
