# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_debt_from_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Locker')], default='N', max_length=1, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=300, verbose_name='name'),
        ),
    ]
