# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_auto_20160828_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='single_subscription',
            field=models.BooleanField(db_index=True, default=True, verbose_name='single subscription'),
        ),
    ]
