# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0014_auto_20160920_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='reported_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.Report'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='reported_in2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_in2', to='facturacion.Report'),
        ),
    ]
