# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_auto_20161004_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_accounting_file',
            field=models.FileField(null=True, upload_to='reports/', verbose_name='staff report file'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_staff_file',
            field=models.FileField(null=True, upload_to='reports/', verbose_name='accounting report file'),
        ),
    ]
