# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0018_auto_20171002_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='billable',
            field=models.BooleanField(db_index=True, default=True, help_text='Desmarquelo para un pago en efectivo', verbose_name='facturar'),
        ),
    ]
