# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 19:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0020_auto_20171006_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory_entry',
        ),
        migrations.AlterField(
            model_name='gift',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity'),
        ),
    ]
