# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0021_auto_20171008_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=False, verbose_name='registrar inventario'),
        ),
    ]
