# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 16:24
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0022_product_track_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(db_index=True, default=datetime.date.today, verbose_name='date')),
                ('billable', models.BooleanField(db_index=True, default=True, help_text='Desmarquelo para un pago en efectivo', verbose_name='facturar')),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='monto')),
                ('concept', models.TextField(verbose_name='concepto')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Student', verbose_name='miembro')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Product', verbose_name='product')),
                ('reported_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.Report')),
            ],
            options={
                'verbose_name': 'Compra Especial',
                'verbose_name_plural': 'Compras Especiales',
                'permissions': (('save_specialpurchase', 'NEW: Can save changes made to the model'),),
            },
        ),
    ]
