# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 18:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0023_specialpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='stock minimo'),
        ),
        migrations.AlterField(
            model_name='specialpurchase',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='monto'),
        ),
    ]
