# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0024_auto_20171013_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minimum_stock',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='stock minimo'),
        ),
    ]
