# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 13:56
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0026_auto_20171023_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(db_index=True, default=datetime.date.today, verbose_name='date')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'Compra en Efectivo',
                'verbose_name_plural': 'Compras en Efectivo',
                'permissions': (('save_purchase', 'NEW: Can save changes made to the model'),),
            },
        ),
        migrations.CreateModel(
            name='CashPurchaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Product', verbose_name='product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.CashPurchase')),
            ],
            options={
                'verbose_name': 'Cash Purchase Item',
                'verbose_name_plural': 'Cash Purchase Items',
                'permissions': (('save_purchaseitem', 'NEW: Can save changes made to the model'),),
            },
        ),
    ]
