# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0027_cashpurchase_cashpurchaseitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashpurchase',
            options={'permissions': (('save_cashpurchase', 'NEW: Can save changes made to the model'),), 'verbose_name': 'Compra en Efectivo', 'verbose_name_plural': 'Compras en Efectivo'},
        ),
        migrations.AlterModelOptions(
            name='cashpurchaseitem',
            options={'permissions': (('save_cashpurchaseitem', 'NEW: Can save changes made to the model'),), 'verbose_name': 'Cash Purchase Item', 'verbose_name_plural': 'Cash Purchase Items'},
        ),
    ]
