# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-07 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0028_auto_20180208_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('f', 'Factura'), ('t', 'Ticket')], db_index=True, max_length=1, verbose_name='Tipo')),
                ('departamento', models.CharField(choices=[('a', 'Agrupaciones'), ('d', 'Deportes'), ('g', 'Gastos Excepcionales'), ('o', 'Gimnasio'), ('i', 'Idiomas'), ('t', 'Internacionales'), ('l', 'La Copia'), ('p', 'Laboratorio'), ('n', 'Nautica'), ('f', 'Oficina'), ('s', 'Servicios')], db_index=True, max_length=1, verbose_name='Departamento')),
                ('concepto', models.CharField(max_length=300, verbose_name='Concepto')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], db_index=True, verbose_name='Mes')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'permissions': (('save_bill', 'NEW: Can save changes made to the model'),),
            },
        ),
    ]
