# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-07 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0029_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='year',
            field=models.PositiveSmallIntegerField(default=2018, verbose_name='Ano'),
        ),
    ]
