# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-12 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0030_bill_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dni',
            field=models.CharField(db_index=True, default='', max_length=10, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='year',
            field=models.PositiveSmallIntegerField(default=2019, verbose_name='Ano'),
        ),
    ]
