# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-12 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0031_auto_20190212_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dni',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10, verbose_name='DNI'),
        ),
    ]
