# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_auto_20160828_1900'),
        ('lockers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockerQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date created')),
                ('locker_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lockers.LockerSite', verbose_name='locker site')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Student', verbose_name='member')),
            ],
            options={
                'verbose_name_plural': 'Locker Queue',
                'verbose_name': 'Locker Queue',
                'ordering': ['locker_site', 'date_created'],
            },
        ),
        migrations.AlterModelOptions(
            name='lockerassignation',
            options={'ordering': ['locker_id'], 'verbose_name': 'Locker Assignation', 'verbose_name_plural': 'Locker Assignation'},
        ),
    ]
