# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0004_lockerassignation_key_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockerassignation',
            name='key_delivered',
            field=models.BooleanField(default=False, help_text='Mark it when the key has been delivered to the member.', verbose_name='key delivered'),
        ),
        migrations.AlterField(
            model_name='lockerqueue',
            name='locker_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lockers.LockerSite', verbose_name='locker site'),
        ),
    ]
