# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0005_auto_20160831_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockerqueue',
            name='locker_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lockers.LockerSite', verbose_name='locker site'),
        ),
    ]
