# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_auto_20160828_1900'),
        ('lockers', '0006_auto_20160831_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockerHold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locker_id', models.PositiveSmallIntegerField(verbose_name='locker id')),
                ('date_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date created')),
                ('locker_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lockers.LockerSite', verbose_name='locker site')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Student', verbose_name='member')),
            ],
            options={
                'verbose_name': 'Locker Hold',
                'permissions': (('save_model', 'Can save changes made to the model'),),
                'ordering': ['locker_site', 'date_created'],
                'verbose_name_plural': 'Locker Hold',
            },
        ),
        migrations.RemoveField(
            model_name='lockerassignation',
            name='key_delivered',
        ),
    ]
