# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0007_auto_20160901_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lockerhold',
            options={'ordering': ['date_created'], 'permissions': (('save_model', 'Can save changes made to the model'),), 'verbose_name': 'Locker Hold', 'verbose_name_plural': 'Locker Hold'},
        ),
    ]
