# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0015_auto_20161004_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, verbose_name='DNI')),
                ('auth_type', models.CharField(choices=[('p', 'Patron'), ('t', 'Timonel')], max_length=1, verbose_name='authorization type')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Student', verbose_name='member')),
            ],
        ),
    ]
