# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='auth_type',
            field=models.CharField(choices=[('p', 'Patron'), ('t', 'Timonel')], default='t', max_length=1, verbose_name='authorization type'),
        ),
    ]
