# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 18:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('sede', models.PositiveSmallIntegerField(choices=[(1, 'Sede Madero'), (3, 'Sede Parque Patricios'), (2, 'Sede Postgrado')], default=1, verbose_name='sede')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='precio')),
                ('important', models.BooleanField(db_index=True, default=False, verbose_name='importante')),
            ],
            options={
                'verbose_name_plural': 'productos del bar',
                'verbose_name': 'producto del bar',
                'permissions': (('save_barproduct', 'NEW: Can save changes made to the model'),),
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='precio')),
                ('order', models.PositiveSmallIntegerField(db_index=True, verbose_name='orden')),
                ('sede', models.PositiveSmallIntegerField(choices=[(1, 'Sede Madero'), (3, 'Sede Parque Patricios'), (2, 'Sede Postgrado')], db_index=True, default=1, verbose_name='sede')),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menues',
                'ordering': ['order'],
                'permissions': (('save_menu', 'NEW: Can save changes made to the model'),),
            },
        ),
        migrations.CreateModel(
            name='MenuDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000, verbose_name='descripción')),
                ('for_date', models.DateField(db_index=True, default=datetime.date.today, verbose_name='para fecha')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.Menu', verbose_name='menú')),
            ],
            options={
                'verbose_name_plural': 'Descripciones de Menú',
                'get_latest_by': 'for_date',
                'verbose_name': 'Descripción de Menú',
                'permissions': (('save_menudescription', 'NEW: Can save changes made to the model'),),
            },
        ),
        migrations.AlterUniqueTogether(
            name='menudescription',
            unique_together=set([('menu', 'for_date')]),
        ),
        migrations.AlterIndexTogether(
            name='menudescription',
            index_together=set([('for_date', 'menu')]),
        ),
    ]
